package automatastarter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import utils.CardSwitcher;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import javax.swing.JPanel;
import utils.ImageUtil;
import javax.swing.Timer;

/**
 *
 * @author michael.roy-diclemen
 */
public class IntroPanel extends javax.swing.JPanel {

    public static final String CARD_NAME = "intro";
    CardSwitcher switcher = null;
    BufferedImage lion;
    BufferedImage deer;
    private Timer animationTimer;
    int lionX = 0;
    int lionY = 100;
    int deerX = 300;
    int deerY = 100;
    int lionSpeed = 10;
    boolean eaten = false;


    /**
     * Creates new form IntroPanel
     */
    public IntroPanel(CardSwitcher p) {
        initComponents();
        // sets up images
        lion = ImageUtil.loadAndResizeImage("lion.png", 300, 300);
        deer = ImageUtil.loadAndResizeImage("deer.png", 300, 300);
        switcher = p;
        animationTimer = new Timer(100, new timerTick());
        animationTimer.start(); 
        

        
        
                
        
    }

    public void paintComponent(Graphics g) {

        super.paintComponent(g);

        //draws the lion & deer
       if (lion != null) {
           g.drawImage(lion, lionX, lionY, this);
       }
        if(deer != null && eaten == false){
            g.drawImage(deer, deerX, deerY, this);
        }

    }
    
    
    
       private class timerTick implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent ae) {
            //moves lion until it catches up with deer
            lionX+= lionSpeed;
            deerX += (lionSpeed/2);
            
            //hides deer when lion catches up
            if(lionX > deerX - 200){
                eaten = true;
                
                //loops over when lion reaches end of screen
                if(lionX > getWidth()){
     
                    lionX = -900;
                    deerX = -300;
                    eaten = false;
                }
                
            }
            
            
            repaint();
            }

        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GameButton = new javax.swing.JButton();
        infoButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setMaximumSize(new java.awt.Dimension(900, 500));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 500));

        GameButton.setText("Game");
        GameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GameButtonActionPerformed(evt);
            }
        });

        infoButton.setText("HELP!");
        infoButton.setToolTipText("");
        infoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(426, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoButton)
                    .addComponent(GameButton))
                .addGap(402, 402, 402))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(GameButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(infoButton)
                .addContainerGap(261, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void GameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GameButtonActionPerformed
        switcher.switchToCard(GamePanel.CARD_NAME);
        
        //ends animation
        animationTimer.stop();
        lionX = -300;
        deerX = -300;
    }//GEN-LAST:event_GameButtonActionPerformed

    private void infoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoButtonActionPerformed
        switcher.switchToCard(InfoPanel.CARD_NAME);
        //ends animation
        animationTimer.stop();
        lionX = -300;
        deerX = -300;
    }//GEN-LAST:event_infoButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GameButton;
    private javax.swing.JButton infoButton;
    // End of variables declaration//GEN-END:variables
}
